image: node:22-alpine

variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"

stages:
  - build
  - deploy

build:
  stage: build
  cache:
    key:
      files:
        - package-lock.json
    paths:
      - .npm/
    policy: pull-push
  before_script:
    - npm ci --prefer-offline --legacy-peer-deps
  script:
    - npm run build
  artifacts:
    paths:
      - dist/
    expire_in: 1 week
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH

deploy_cloudflare_pages:
  stage: deploy
  image: node:22-alpine
  dependencies:
    - build
  before_script:
    - npm install -g wrangler
  script:
    - wrangler pages deploy dist/ --project-name=home
  environment:
    name: production
    url: https://adenyrr.me
  needs:
    - job: build_site
      artifacts: true
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'